---
######################################################################
# NOTE: These are duplicated from roles/openshift_master/handlers/main.yml
#
# TODO: Use the consolidated 'openshift_handlers' role once it's ready
# See: https://github.com/openshift/openshift-ansible/pull/4041#discussion_r118770782
######################################################################

- name: restart master api
  systemd: name={{ openshift.common.service_type }}-master-api state=restarted
  when: (not (master_api_service_status_changed | default(false) | bool)) and openshift.master.cluster_method == 'native'
  notify: Verify API Server

- name: restart master controllers
  systemd: name={{ openshift.common.service_type }}-master-controllers state=restarted
  when: (not (master_controllers_service_status_changed | default(false) | bool)) and openshift.master.cluster_method == 'native'

- name: Verify API Server
  # Using curl here since the uri module requires python-httplib2 and
  # wait_for port doesn't provide health information.
  command: >
    curl --silent --tlsv1.2
    {% if openshift.common.version_gte_3_2_or_1_2 | bool %}
    --cacert {{ openshift.common.config_base }}/master/ca-bundle.crt
    {% else %}
    --cacert {{ openshift.common.config_base }}/master/ca.crt
    {% endif %}
    {{ openshift.master.api_url }}/healthz/ready
  args:
    # Disables the following warning:
    # Consider using get_url or uri module rather than running curl
    warn: no
  register: api_available_output
  until: api_available_output.stdout == 'ok'
  retries: 120
  delay: 1
  changed_when: false

- name: OpenShift-CFME - Reload NFS Exports
  command: exportfs -ar
