---
# Namespace for the CFME project
openshift_cfme_project: openshift-cfme
# Namespace/project description
openshift_cfme_project_description: CloudForms Management Engine

######################################################################
# BASE TEMPLATE AND DATABASE OPTIONS
######################################################################
# Which flavor of CFME would you like? You may install CFME using a
# podified PostgreSQL server, or you may choose to use an existing
# PostgreSQL server.
#
# Choose 'miq-template' for a podified database install
# Choose 'miq-template-ext-db' for an external database install
openshift_cfme_app_template: miq-template

# If you are using the miq-template-ext-db template then you must add
# the required database parameters to the
# openshift_cfme_template_parameters variable. You only need to
# provide parameters that differ from the ones in the following
# example. Any omitted parameter by the user will be default to its
# default below:
#
# openshift_cfme_template_parameters:
#   DATABASE_USER: 'root'
#   DATABASE_PASSWORD: ''
#   DATABASE_IP: '10.1.1.10'
#   DATABASE_PORT: 5432
#   DATABASE_NAME: 'vmdb_production'
#
# See also parameter: __openshift_cfme_default_db_connection_info

######################################################################
# STORAGE OPTIONS
######################################################################
# DEFAULT - 'nfs'
# Allowed options: nfs, nfs_external, preconfigured, cloudprovider.
openshift_cfme_storage_class: nfs
# * nfs - Best used for proof-of-concept installs. Will setup NFS on a
#   cluster host (defaults to your first master in the inventory file)
#   to back the required PVCs. The application requires a PVC and the
#   database (which may be hosted externally) may require a
#   second. PVC minimum required sizes are: 5GiB for the MIQ
#   application, and 15GiB for the PostgreSQL database (20GiB minimum
#   available space on an volume/partition if used specifically for
#   NFS purposes)
#
# * nfs_external - You are using an external NFS server, such as a
#   netapp appliance. See the STORAGE - NFS OPTIONS section below for
#   required information.
#
# * preconfigured - This CFME role will do NOTHING to modify storage
#   settings. This option assumes expert knowledge and that you have
#   done everything required ahead of time.
#
# * cloudprovider - You are using an OCP cloudprovider integration for
#   your storage class. For this to work you must have already
#   configured the required inventory parameters for your cloud
#   provider
#
#   Ensure 'openshift_cloudprovider_kind' is defined (aws or gce) and
#   that the applicable cloudprovider parameters are provided.

#---------------------------------------------------------------------
# STORAGE - NFS OPTIONS
#---------------------------------------------------------------------
# [OPTIONAL] - If you are using an EXTERNAL NFS server, such as a
# netapp appliance, then you must set the hostname here. Leave the
# value as 'false' if you are not using external NFS.
openshift_cfme_storage_nfs_external_hostname: false
# [OPTIONAL] - If you are using external NFS then you must set the base
# path to the exports location here.
#
# Additionally: EXTERNAL NFS REQUIRES that YOU CREATE the nfs exports
# that will back the application PV and optionally the database
# pv. Export path definitions, relative to
# {{ openshift_cfme_storage_nfs_base_dir }}
#
# * REQUIRED[ALWAYS]: /miq-app - MIQ Server PV.
#
# * REQUIRED[NFS_EXTERNAL]: /miq-db - Podified DB PB
#
# LOCAL NFS NOTE:
#
# You may may also change this value if you want to change the default
# path used for local NFS exports.
openshift_cfme_storage_nfs_base_dir: /exports

#---------------------------------------------------------------------
# DEFAULT PV SIZES
# How large to make the MIQ application PV
openshift_cfme_app_pv_size: 5Gi
# How large to make the MIQ PostgreSQL PV
openshift_cfme_db_pv_size: 15Gi

######################################################################
# VARIOUS CONSTANTS - DO NOT OVERRIDE THESE UNDER ANY CIRCUMSTANCES
######################################################################
# Misc enumerated values
#---------------------------------------------------------------------
# Allowed choices for the storage class parameter
__openshift_cfme_storage_classes:
  - nfs
  - nfs_external
  - preconfigured
  - cloudprovider
# Name of the application templates with object/parameter definitions
__openshift_cfme_app_templates:
  - miq-template-ext-db
  - miq-template
# PostgreSQL database connection parameters
__openshift_cfme_db_parameters:
  - DATABASE_USER
  - DATABASE_PASSWORD
  - DATABASE_IP
  - DATABASE_PORT
  - DATABASE_NAME


######################################################################
# ACCOUNTING
######################################################################
# Service Account SSCs
__openshift_system_account_sccs:
  - name: miq-anyuid
    resource_name: anyuid
  - name: miq-orchestrator
    resource_name: anyuid
  - name: miq-privileged
    resource_name: privileged
  - name: miq-httpd
    resource_name: miq-httpd
  - name: miq-httpd
    resource_name: anyuid

# Service Account Roles
__openshift_cfme_system_account_roles:
  - name: miq-orchestrator
    resource_name: view
  - name: miq-orchestrator
    resource_name: edit

######################################################################
# DEFAULTS
######################################################################
# User only has to provide parameters they need to override, we will
# do a hash update method with the provided user parameters to create
# the final connection structure.
__openshift_cfme_default_db_connection_info:
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: ''
  DATABASE_IP: ''
  DATABASE_PORT: 5432
  DATABASE_NAME: 'vmdb_production'

######################################################################
# SCAFFOLDING - These are parameters we pre-seed that a user may or
# may not set later
######################################################################
# A hash of parameters you want to override or set in the
# miq-template.yaml or miq-template-ext-db.yaml templates. Set this in
# your inventory file as a simple hash. Acceptable values are defined
# under the .parameters list in files/miq-template{-ext-db}.yaml
# Example:
#
# openshift_cfme_template_parameters={'APPLICATION_MEM_REQ': '512Mi'}
openshift_cfme_template_parameters: {}

# TODO: Refactor '_install_app' variable. This is just for testing but
# maybe in the future it should control the entire yes/no for CFME.
#
# Whether or not the manageiq app should be initialized ('oc new-app
# --template=manageiq). If False everything UP TO 'new-app' is ran.
openshift_cfme_install_app: False
# Docker image to pull
# openshift_cfme_application_img_name: "{{ 'registry.access.redhat.com/cloudforms46/cfme-openshift-app' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
# openshift_cfme_application_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'frontend-latest' }}"

# openshift_cfme_memcached_img_name: "{{ 'registry.access.redhat.com/cloudforms46/cfme-openshift-memcached' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
# openshift_cfme_memcached_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'memcached-latest-fine' }}"

# openshift_cfme_postgresql_img_tag: "{{ 'latest' if openshift_deployment_type == 'openshift-enterprise' else 'postgresql-latest-fine' }}"
# openshift_cfme_postgresql_img_name: "{{ 'registry.access.redhat.com/cloudforms46/cfme-openshift-postgresql' if openshift_deployment_type == 'openshift-enterprise' else 'docker.io/manageiq/manageiq-pods' }}"
